---
Mappings:
- modelMapping:
    sourceModel: userRole
    targetModel: LoginUserRole
    fieldMapping:
    - sourceField: roleID
      targetField: roleID
    - sourceField: role
      targetField: role
    - sourceField: name
      targetField: name
    - sourceField: description
      targetField: description