---
Mappings:
- modelMapping:
    sourceModel: user
    targetModel: LoginUser
    fieldMapping:
    - sourceField: userPassword
      targetField: password
    - sourceField: userName
      targetField: userName
      #where communicationChannelCode ="EMAIL"
    - sourceField: communicationChannel.communicationValue
      targetField: email
    - sourceField: isWindowsUser
      targetField: isWindowsUser
    #where communicationChannelCode ="IPADDRESS"
    - sourceField: communicationChannel.communicationValue
      targetField: ipAddress
    - sourceField: comments
      targetField: userComments
    - sourceField: security.securityQuestion
      targetField: pwdQuestion
    - sourceField: security.securityAnswer
      targetField: pwdAnswer
    - sourceField: userId
      targetField: userId
    - sourceField: password
      targetField: password
    - sourceField: email
      targetField: email