name: Python package
on:
  push:
    branches: [ master ]
jobs:
  build:
    steps:
    - name : docker login
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    runs-on: ubuntu-latest
    container:
      image: 926817/webcenter/activemq
      ports:
        - 5000:5000
      credentials:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
     
