name: Python package
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: build image
      run: |
        cd git-docker
        docker build -t application-git .
    - name: docker-push
      run: |
        docker tag application-git 926817/application-git
        docker push 926817/application-git
    container:
      image: 926817:926817/application-git
      ports:
        - 5000:5000
