name: Python package
on:
  push:
    branches: [ master ]
jobs:
  build:
    steps:
    - name: docker-push
      run: |
        echo hiu
    - name: curl
      uses: wei/curl@master
      with:
        args: http://localhost:5000/
    runs-on: ubuntu-latest
    services:
      APPPP:
        image: myapp2
        ports:
          - 5000:5000
        credentials:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
