name: Python package
on:
  push:
    branches: [ master ]
jobs:
  build:
    steps:
    - name: docker-push
      run: |
        echo hi
    - name: post a user example
      run: curl --request GET http://localhost:5000/
    runs-on: ubuntu-latest
    container:
      image: 926817/application-git
      ports:
        - 5000:5000
      credentials:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
