name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  job1:
    name: deploy
    runs-on: windows-latest
    steps:
    - name: download git file
      uses: actions/checkout@v2
    - name: configuration changes
      run: 
        echo "hi"
        echo "hello"
        cd ${{github-workspace}}
