name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  job1:
    name: deploy
    runs-on: windows-latest
    steps:
    - name: download git file
      uses: actions/checkout@v2
    - name: configuration changes
      run: | 
        echo hi %1
        echo hellos
        dir
        cd plat-con-catman-adapter
        dir
        cmd "ping www.google.com"
        cmd  "ping http://md1npdvjdapc01:9811/cps/api/v1/application/pyadapter/properties?environment=local"
        cmd "ping http://admin:admin@localhost:8161/admin/queues.jsp"
