name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  job1:
    name: deploy
    runs-on: windows-latest
    steps:
    - name: download git file
      uses: actions/checkout@v2
    - name: configuration changes
      run: | 
        cd pycatmanadapter
        echo python -m pip install pyinstaller
        echo pyinstaller -p pycatmanadapter launch.py
        xcopy  "config_repo"  "dist\launch\config_repo" /e /i /h

