name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: build executable
    runs-on: windows-latest
    steps:
    - name: docker-login
      env:
        DOCKER_USER: ${{Secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{Secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
