
name: Python package

on:
  push:
    branches: [ master ]
jobs:
  build:
    name: build executable
    runs-on: windows-latest
    steps:
    - name: download git file
      uses: actions/checkout@v2
    - name: install yamale
      run: |
        pip install yamale
    - name: validate yaml files
      run: |
        cd pycatmanadapter\config_repo\pyadapter\local\master\resources
        yamale --schema schema.yaml
