name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  job1:
    name: deploy
    runs-on: windows-latest
    steps:
    - name: download git file
      uses: actions/checkout@v2
    - name: configuration changes
      run: | 
        echo hi %1
        echo hellos
        echo path of pycatmanadapter whereyou installed
        cd plat-con-catman-adapter
        echo python -m pip install -e.
        dir
        cd plat-con-catman-adapter/pycatmanadapter
        ech python -m pip install pyinstaller
        echo pyinstaller -p pycatmanadapter launch.py
        echo curl -v www.google.com
        echo curl -v http://admin:admin@localhost:8161/admin/queues.jsp
        echo cmd "ping  www.google.com"
        echo cmd  "ping http://md1npdvjdapc01:9811/cps/api/v1/application/pyadapter/properties?environment=local"
        echo md "ping http://admin:admin@localhost:8161/admin/queues.jsp"
