name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  job1:
    name: deploy
    runs-on: windows-latest
    steps:
    - name: download git file
      uses: actions/checkout@v2
    - name: configuration changes
      run: | 
        cd pycatmanadapter
        python -m pip install pyinstaller
        pyinstaller -p pycatmanadapter launch.py
        xcopy  "%1\plat-con-catman-adapter\pycatmanadapter\config_repo"  "%1\plat-con-catman-adapter\pycatmanadapter\dist\launch\config_repo" /e /i /h
mkdir %1\plat-con-catman-adapter\pycatmanadapter\dist\launch\connect

