name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  job1:
    name: deploy
    runs-on: windows-latest
    steps:
    - name: download git file
      uses: actions/checkout@v2
    - name: configuration changes
      run: | 
        cd pycatmanadapter
        echo python -m pip install pyinstaller
        echo pyinstaller -p pycatmanadapter launch.py
        echo xcopy  "config_repo"  "dist\launch\config_repo" /e /i /h
        echo mkdir dist\launch\connect
        echo mkdir dist\launch\connect\cps
        copy connect\cps\adapter-cps.json dist\launch\connect\cps\
        mkdir dist\launch\log
        mkdir dist\launch\log\archived

